# fly.toml app configuration file for Pelican Property Management
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pelicantimesubmission'
primary_region = 'dfw'

[build]
  [build.args]
    REACT_APP_GOOGLE_CLIENT_ID = ""
    REACT_APP_ADMIN_PASSWORD = ""

[env]
  PORT = "8080"
  NODE_ENV = "production"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
